### PR TITLE
CORE-1753: remove support for CAS

### PR DESCRIPTION
**Pull request by slr71**
This change will have to be tested directly in the QA environment, so I'm requesting a review even though no actual integration testing has been done yet.

### CODE REVIEW

**Review by johnworth — APPROVED** [review]
LGTM :shipit:

**Review by ianmcorvidae — APPROVED** [review]
This all looks reasonable to me. Nice to rename the type as well, was briefly confusing me looking at this code yesterday.

**Review by psarando — APPROVED** [review]
LGTM 👍

**Comment by slr71** [comment]
Thanks for the reviews!

**Pull request merged**
